// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TEST05.Migrations
{
    [DbContext(typeof(BAITHI))]
    [Migration("20230628082934_create_table_DonHang")]
    partial class create_table_DonHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TEST05.Models.DonHang", b =>
                {
                    b.Property<string>("MaKhach")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoLuong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhach");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("TEST05.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhach")
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhach");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("TEST05.Models.DonHang", b =>
                {
                    b.HasOne("TEST05.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
